# Global ARGs - must be declared before the first FROM to be usable in any FROM instruction
ARG ALPINE_VERSION=3.23
ARG NODE_VERSION=20.20

# Build stage
FROM node:20.20-alpine3.23 AS development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install glob rimraf

RUN npm install --include=dev

COPY . .

RUN npm run build

# Production stage
FROM node:${NODE_VERSION}-alpine${ALPINE_VERSION} AS production

RUN apk upgrade --no-cache

RUN adduser -D nestjs

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --omit=dev

COPY . .

COPY --from=development /usr/src/app/dist ./dist

RUN chown -R nestjs:nestjs /usr/src/app

USER nestjs

CMD ["node", "dist/main"]
